#include "voice_listening_led.h"

#include "adapter.h"

#include <stdlib.h>
#include <string.h>

/*
 * A short chirp when the device starts listening.
 *
 * Without it there is no way to tell a missed wake word from a wake that
 * fired and heard nothing -- the ring is the only feedback, and it is easy
 * to miss or deliberately turned off.  The sound is generated by audiod on
 * the system bus, so it is the same path the echo canceller references and
 * does not need its own asset.
 *
 * Best effort: if audiod is unavailable the device still listens, it just
 * does so silently, which is better than refusing the turn.
 */
static void le_voice_listening_chirp(void)
{
    struct le_adapter *adapter;

    if (getenv("LE_VOICE_WAKE_CHIRP") &&
        !strcmp(getenv("LE_VOICE_WAKE_CHIRP"), "0"))
        return;
    adapter = le_adapter_connect(LE_ADAPTER_AUDIO_SOCK, 100);
    if (!adapter)
        return;
    (void)le_adapter_call(adapter, "wake_chirp", NULL, NULL, 0);
    le_adapter_close(adapter);
}

void le_voice_listening_led_set(int active)
{
    struct le_adapter *adapter;
    const char *args;

    if (active)
        le_voice_listening_chirp();

    adapter = le_adapter_connect(LE_ADAPTER_LED_SOCK, 100);
    if (!adapter)
        return;
    args = active
        ? "{\"name\":\"pulse\",\"r\":255,\"g\":0,\"b\":0,\"brightness\":70,\"repeats\":0,\"owner\":\"voice-listening\"}"
        : "{\"name\":\"stop\",\"owner\":\"voice-listening\"}";
    (void)le_adapter_call(adapter, "pattern", args, NULL, 0);
    /*
     * waked lights its own red pulse on the wake word and clears it on a
     * fixed five-second timer, independently of how long the turn actually
     * runs.  Recognition normally ends well before that, so dropping only
     * the listening pattern left the ring red for the remainder of the wake
     * window -- the device looked like it was still recording seconds after
     * it had stopped, which is exactly the wrong thing for a microphone
     * indicator to do.  Clear the wake owner too once recognition ends;
     * waked's own expiry is idempotent and simply finds it already stopped.
     */
    if (!active)
        (void)le_adapter_call(
            adapter, "pattern",
            "{\"name\":\"stop\",\"owner\":\"wakeword\"}", NULL, 0);
    le_adapter_close(adapter);
}
