#include "backend_internal.h"
#include <stdlib.h>
#include <string.h>
int le_backend_init(struct le_backend **out,const char *mode,const char *mock,const char *cfg,unsigned seed){struct le_backend*b;if(!out)return LE_INVALID;b=calloc(1,sizeof(*b));if(!b)return LE_IO;strncpy(b->mode,mode?mode:"mock",15);if((!strcmp(b->mode,"mock")?le_mock_create(b,mock,cfg,seed):!strcmp(b->mode,"linux")?le_linux_create(b,cfg):LE_INVALID)!=LE_OK){free(b);return LE_INVALID;}*out=b;return LE_OK;}
void le_backend_destroy(struct le_backend*b){if(b){if(b->ops&&b->ops->destroy)b->ops->destroy(b);free(b);}}
const char*le_backend_mode(struct le_backend*b){return b?b->mode:"unknown";}
const char*le_result_code(int r){switch(r){case LE_INVALID:return"invalid_request";case LE_NOT_SUPPORTED:return"not_supported";case LE_IO:return"io_error";case LE_BUSY:return"busy";case LE_AUTH:return"forbidden";default:return"internal_error";}}
int le_get_system_status(struct le_backend*b,struct le_system_status*o){return b&&b->ops->status?b->ops->status(b,o):LE_NOT_SUPPORTED;} int le_get_device_info(struct le_backend*b,struct le_device_info*o){return b&&b->ops->device?b->ops->device(b,o):LE_NOT_SUPPORTED;}
int le_get_audio_state(struct le_backend*b,struct le_audio_state*o){return b&&b->ops->audio?b->ops->audio(b,o):LE_NOT_SUPPORTED;} int le_set_volume(struct le_backend*b,int v){return b&&b->ops->volume?b->ops->volume(b,v):LE_NOT_SUPPORTED;} int le_set_microphone_gain(struct le_backend*b,int v){return b&&b->ops->gain?b->ops->gain(b,v):LE_NOT_SUPPORTED;} int le_set_microphone_muted(struct le_backend*b,int v){return b&&b->ops->mute?b->ops->mute(b,v):LE_NOT_SUPPORTED;} int le_play_test_tone(struct le_backend*b){return b&&b->ops->tone?b->ops->tone(b):LE_NOT_SUPPORTED;} int le_set_tts_voice(struct le_backend*b,const char*v){return b&&b->ops->tts_voice?b->ops->tts_voice(b,v):LE_NOT_SUPPORTED;} int le_announce(struct le_backend*b,const char*t){return b&&b->ops->announce?b->ops->announce(b,t):LE_NOT_SUPPORTED;} int le_stop_speech(struct le_backend*b){return b&&b->ops->stop_speech?b->ops->stop_speech(b):LE_NOT_SUPPORTED;}
int le_get_led_state(struct le_backend*b,struct le_led_state*o){return b&&b->ops->led?b->ops->led(b,o):LE_NOT_SUPPORTED;} int le_set_led_colour(struct le_backend*b,uint8_t r,uint8_t g,uint8_t bl){return b&&b->ops->colour?b->ops->colour(b,r,g,bl):LE_NOT_SUPPORTED;} int le_set_led_brightness(struct le_backend*b,int v){return b&&b->ops->brightness?b->ops->brightness(b,v):LE_NOT_SUPPORTED;} int le_set_led_visualizer_enabled(struct le_backend*b,int v){return b&&b->ops->visualizer_enabled?b->ops->visualizer_enabled(b,v):LE_NOT_SUPPORTED;} int le_set_boot_led(struct le_backend*b,const struct le_led_profile*p){return b&&b->ops->boot_led?b->ops->boot_led(b,p):LE_NOT_SUPPORTED;} int le_set_led_profile(struct le_backend*b,const char*n,const struct le_led_profile*p){return b&&b->ops->profile?b->ops->profile(b,n,p):LE_NOT_SUPPORTED;} int le_set_led_night(struct le_backend*b,int e,int st,int en){return b&&b->ops->night?b->ops->night(b,e,st,en):LE_NOT_SUPPORTED;} int le_run_led_test(struct le_backend*b){return b&&b->ops->led_test?b->ops->led_test(b):LE_NOT_SUPPORTED;}
int le_get_network_state(struct le_backend*b,struct le_network_state*o){return b&&b->ops->network?b->ops->network(b,o):LE_NOT_SUPPORTED;} int le_scan_wifi(struct le_backend*b,struct le_wifi_scan*o){return b&&b->ops->scan?b->ops->scan(b,o):LE_NOT_SUPPORTED;} int le_connect_wifi(struct le_backend*b,const struct le_wifi_credentials*c){return b&&b->ops->connect?b->ops->connect(b,c):LE_NOT_SUPPORTED;} int le_disconnect_wifi(struct le_backend*b){return b&&b->ops->disconnect?b->ops->disconnect(b):LE_NOT_SUPPORTED;} int le_set_hostname(struct le_backend*b,const char*s){return b&&b->ops->hostname?b->ops->hostname(b,s):LE_NOT_SUPPORTED;}
int le_get_wake_word_state(struct le_backend*b,struct le_wake_word_state*o){return b&&b->ops->wake?b->ops->wake(b,o):LE_NOT_SUPPORTED;} int le_set_wake_word(struct le_backend*b,const char*s){return b&&b->ops->wake_set?b->ops->wake_set(b,s):LE_NOT_SUPPORTED;} int le_set_wake_word_sensitivity(struct le_backend*b,int v){return b&&b->ops->sensitivity?b->ops->sensitivity(b,v):LE_NOT_SUPPORTED;} int le_test_wake_word(struct le_backend*b){return b&&b->ops->wake_test?b->ops->wake_test(b):LE_NOT_SUPPORTED;} int le_reboot(struct le_backend*b){return b&&b->ops->reboot?b->ops->reboot(b):LE_NOT_SUPPORTED;} int le_shutdown(struct le_backend*b){return b&&b->ops->shutdown?b->ops->shutdown(b):LE_NOT_SUPPORTED;} int le_factory_reset(struct le_backend*b){return b&&b->ops->reset?b->ops->reset(b):LE_NOT_SUPPORTED;} int le_backend_tick(struct le_backend*b){return b&&b->ops->tick?b->ops->tick(b):LE_NOT_SUPPORTED;}
int le_get_bluetooth_state(struct le_backend*b,struct le_bluetooth_state*o){return b&&b->ops->bluetooth?b->ops->bluetooth(b,o):LE_NOT_SUPPORTED;} int le_set_bluetooth_enabled(struct le_backend*b,int v){return b&&b->ops->bluetooth_set?b->ops->bluetooth_set(b,v):LE_NOT_SUPPORTED;}
int le_bluetooth_scan(struct le_backend*b,int start){return b&&b->ops->bluetooth_scan?b->ops->bluetooth_scan(b,start):LE_NOT_SUPPORTED;} int le_bluetooth_pair(struct le_backend*b,const char*a,int t,int c){return b&&b->ops->bluetooth_pair?b->ops->bluetooth_pair(b,a,t,c):LE_NOT_SUPPORTED;} int le_bluetooth_unpair(struct le_backend*b,const char*a,int t){return b&&b->ops->bluetooth_unpair?b->ops->bluetooth_unpair(b,a,t):LE_NOT_SUPPORTED;} int le_bluetooth_disconnect(struct le_backend*b,const char*a,int t){return b&&b->ops->bluetooth_disconnect?b->ops->bluetooth_disconnect(b,a,t):LE_NOT_SUPPORTED;} int le_bluetooth_pairing_response(struct le_backend*b,const char*a,int t,const char*m,unsigned int v,const char*p){return b&&b->ops->bluetooth_pairing_response?b->ops->bluetooth_pairing_response(b,a,t,m,v,p):LE_NOT_SUPPORTED;} int le_bluetooth_set_discoverable(struct le_backend*b,int v){return b&&b->ops->bluetooth_discoverable?b->ops->bluetooth_discoverable(b,v):LE_NOT_SUPPORTED;} int le_bluetooth_set_connectable(struct le_backend*b,int v){return b&&b->ops->bluetooth_connectable?b->ops->bluetooth_connectable(b,v):LE_NOT_SUPPORTED;} int le_bluetooth_set_pairing_mode(struct le_backend*b,int v){return b&&b->ops->bluetooth_pairing_mode?b->ops->bluetooth_pairing_mode(b,v):LE_NOT_SUPPORTED;}
int le_get_airplay_state(struct le_backend*b,struct le_airplay_state*o){return b&&b->ops->airplay?b->ops->airplay(b,o):LE_NOT_SUPPORTED;} int le_set_airplay_enabled(struct le_backend*b,int v){return b&&b->ops->airplay_set?b->ops->airplay_set(b,v):LE_NOT_SUPPORTED;}
int le_get_playback_state(struct le_backend*b,struct le_playback_state*o){return b&&b->ops->playback?b->ops->playback(b,o):LE_NOT_SUPPORTED;}
int le_backend_mock_control(struct le_backend*b,const char*a,const char*v){return b&&b->ops->control?b->ops->control(b,a,v):LE_NOT_SUPPORTED;}
